### ISSUE TITLE
Data Manager: Track open observables

### ISSUE THREAD

**Issue by alxhub** [angular/tactical#13]
The Data Manager should keep track of requests made by the application and which Observables are still active. This information should be organized to make it easy to deliver future updates.

**Comment by ttowncompiled** [comment]
Inside of the observe function, we can create a hook that registers the resulting observable with the Data Manager. See issue: #12 

We would also place a callback on the observable that removes the observable from the registry whenever it becomes closed.

**Comment by alxhub** [comment]
Implemented in #24
