### ISSUE TITLE
Data Manager: Service application request to fetch data

### ISSUE THREAD

**Issue by alxhub** [angular/tactical#15]
Handle an application request to fetch data by key, replicating the request to both the local store and the backend if necessary.

**Comment by ttowncompiled** [comment]
Inside of the getter functions (see issue: #12 ), we can call fetch on the Tactical Store (see issue: #7 ). If fetch returns **null**, then we send a request to the backend to service the provided key.

If the backend is required to service the request, once the Data Manager receives a response from the server, it will need to commit that object to the Tactical Store (see issue: #7).

Either way, once the Data Manager has the object requested by the application, it needs to emit that object respective to the getter that was called (see issue: #12 ).

**Comment by alxhub** [comment]
Partially complete by #24 - integration with Tactical Store is missing.
