### ISSUE TITLE
Some test specs run twice

### ISSUE THREAD

**Issue by alxhub** [angular/tactical#26]
When I run `gulp test`, I see the `JSON serializer` and `InMemoryIdb` specifications appear twice in the output.

**Comment by ttowncompiled** [comment]
I ran ```gulp test``` inside of master and did not see any redundancies. Could this be something specific to one of your branches?

**Comment by alxhub** [comment]
Turns out it's specific to my working copy - I had extra files under dist/.

Working as intended, though we should probably clear dist/ before we build.

**Comment by ttowncompiled** [comment]
See issue #28
