### ISSUE TITLE
Tactical Store: Abstraction Layer over IndexedDB (for testing)

### ISSUE THREAD

**Issue by alxhub** [angular/tactical#8]
Unfortunately, IndexedDB is not very testable, which makes testing Tactical Store problematic. To avoid this, we will implement a basic abstraction layer for IndexedDB, with both a mock and a real implementation.

**Comment by ttowncompiled** [comment]
I think what we might need is a mock Tactical Store to test the application calls to Data Manager. Then, Tactical Store will be the real implementation.

As for other features that the Tactical Store provides, we can test those separately.

**Comment by ttowncompiled** [comment]
/**
 * A very minimal interface for a key-value store, designed as an abstraction
 * layer over IndexedDB.
 */
interface Idb {
  get(key: string): Promise<Object>;
  put(key: string, value: Object): Promise<boolean>;
  remove(key: string): Promise<boolean>;
}

**Comment by alxhub** [comment]
Closed by #21.
